source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ClientDetails_Example', :exclusive => true do
  pod 'ClientDetails', :path => '../'
end

target 'ClientDetails_Tests', :exclusive => true do
  pod 'ClientDetails', :path => '../'

  
end
